KT0720_61133181/KT0720_61133181/Controllers/SINHVIEN0720_61133181Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KT0720_61133181.Models;

namespace KT0720_61133181.Controllers
{
    public class SINHVIEN0720_61133181Controller : Controller
    {
        private KT0720_61133181Entities db = new KT0720_61133181Entities();
        string LayMaNV()
        {
            var maMax = db.SINHVIENs.ToList().Select(n => n.MaSV).Max();
            int maSV = int.Parse(maMax.Substring(2)) + 1;
            string SV = String.Concat("000", maSV.ToString());
            return "SV" + SV.Substring(maSV.ToString().Length - 1);
        }
        public ActionResult TimKiem_61133181()
        {
            var sinhViens = db.SINHVIENs.Include(n => n.LOP);
            return View(sinhViens.ToList());
        }
        [HttpPost]
        public ActionResult TimKiem_61133181(string maSV)
        {

            //var nhanViens = db.NhanViens.SqlQuery("exec NhanVien_DS '"+maNV+"' ");
            var sinhViens = db.SINHVIENs.SqlQuery("SELECT * FROM SINHVIEN WHERE MaSV='" + maSV + "'");
            //var sinhViens = db.SINHVIENs.Where(abc =>abc.MaSV==maSV);
            return View(sinhViens.ToList());
        }
        [HttpGet]


        // GET: SINHVIEN0720_61133181
        public ActionResult Index()
        {
            var sINHVIENs = db.SINHVIENs.Include(s => s.LOP);
            return View(sINHVIENs.ToList());
        }

        // GET: SINHVIEN0720_61133181/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            return View(sINHVIEN);
        }

        // GET: SINHVIEN0720_61133181/Create
        public ActionResult Create()
        {
            ViewBag.MaLop = new SelectList(db.LOPs, "MaLop", "TenLop");
            return View();
        }

        // POST: SINHVIEN0720_61133181/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSV,HoSV,TenSV,NgaySinh,GioiTinh,AnhSV,DiaChi,MaLop")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                db.SINHVIENs.Add(sINHVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLop = new SelectList(db.LOPs, "MaLop", "TenLop", sINHVIEN.MaLop);
            return View(sINHVIEN);
        }

        // GET: SINHVIEN0720_61133181/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLop = new SelectList(db.LOPs, "MaLop", "TenLop", sINHVIEN.MaLop);
            return View(sINHVIEN);
        }

        // POST: SINHVIEN0720_61133181/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSV,HoSV,TenSV,NgaySinh,GioiTinh,AnhSV,DiaChi,MaLop")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sINHVIEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLop = new SelectList(db.LOPs, "MaLop", "TenLop", sINHVIEN.MaLop);
            return View(sINHVIEN);
        }

        // GET: SINHVIEN0720_61133181/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            return View(sINHVIEN);
        }

        // POST: SINHVIEN0720_61133181/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            db.SINHVIENs.Remove(sINHVIEN);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KT0720_61133181/KT0720_61133181/Views/SINHVIEN0720_61133181/Create.cshtml
@model KT0720_61133181.Models.SINHVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>NHẬP THÔNG TIN SINH VIÊN</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSV,"Mã sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoSV, "Họ sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSV, "Tên sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, "Ngay sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSV, "Ảnh sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.AnhSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLop, "Mã lớp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

KT0720_61133181/KT0720_61133181/Views/SINHVIEN0720_61133181/Delete.cshtml
@model KT0720_61133181.Models.SINHVIEN

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SINHVIEN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LOP.TenLop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOP.TenLop)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KT0720_61133181/KT0720_61133181/Views/SINHVIEN0720_61133181/Details.cshtml
@model KT0720_61133181.Models.SINHVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string gtinh = "";
}

<table border="1" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
    <tr>
        <td>
            <table cellpadding="2" cellspacing="10">
                <caption><b>THÔNG TIN CHI TIẾT</b></caption>
                <tr>
                    <td rowspan="8"><img src="/Images/@Html.DisplayFor(model => model.AnhSV)" width="100" height="100" /></td>
                    <td>Mã nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.MaSV)</td>
                </tr>
                <tr>
                    <td>Họ nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.HoSV)</td>
                </tr>
                <tr>
                    <td>Tên nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.TenSV)</td>
                </tr>
                <tr>
                    <td>Giới tính:</td>
                    <td>
                        @{if (Model.GioiTinh == true)
                            { gtinh = "Nam"; }
                            else
                            { gtinh = "Nữ"; }
                        }
                        @gtinh
                    </td>
                </tr>
                <tr>
                    <td>Ngày sinh:</td>
                    <td>@Html.DisplayFor(model => model.NgaySinh)</td>
                </tr>
                <tr>
                    <td>Địa chỉ:</td>
                    <td>@Html.DisplayFor(model => model.DiaChi)</td>
                </tr>
                <tr>
                    <td>Phòng ban:</td>
                    <td>@Html.DisplayFor(model => model.LOP.MaLop)</td>
                </tr>

            </table>
        </td>
    </tr>
</table>

KT0720_61133181/KT0720_61133181/Views/SINHVIEN0720_61133181/Edit.cshtml
@model KT0720_61133181.Models.SINHVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
                    $(function ()
                    {
                        var fileupload = $("#Avatar");
                        var image = $("#FileUpload");
                        image.click(function ()
                        {
                            fileupload.click();
                        });
                        fileupload.change(function ()
                        {
                            var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
                            document.getElementById("AnhSV").value=fileName;
                        });
                    });
    </script>
}

<h2>THÔNG TIN CHI TIẾT</h2>

@using (Html.BeginForm("Edit", "../SINHVIEN0720_61133181", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSV)

        <div class="form-group">
            @Html.LabelFor(model => model.HoSV, "Họ sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSV, "Tên sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">

                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSV, "Ảnh sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhSV, "", new { @class = "text-danger" })
                <input type="file" name="Avatar" id="Avatar" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLop, "Mã lớp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KT0720_61133181/KT0720_61133181/Views/SINHVIEN0720_61133181/Index.cshtml
@model IEnumerable<KT0720_61133181.Models.SINHVIEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 2);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<div id="gridContent">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
     grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("MaSV","Mã sinh viên"), //the model fields to display
    grid.Column("HoSV","Họ sinh viên"  ),
    grid.Column("TenSV","Tên sinh viên"),
    grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
    grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("LOP.MaLop","Mã lớp"),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","SINHVIEN0720_61133181", new { id = item.MaSV },"SINHVIEN0720_61133181Controller")),

}
)
</div>

KT0720_61133181/KT0720_61133181/Views/SINHVIEN0720_61133181/TimKiem_61133181.cshtml
@model IEnumerable<KT0720_61133181.Models.SINHVIEN>

@{
    ViewBag.Title = "TimKiem_61133181";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 2);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

@using (Html.BeginForm())
{
    <p style="text-align:center">Mã sinh viên<input type="text" name="maSV" /></p>
    <p style="text-align:center">Họ tên<input type="text" name="hoTen" /></p>
    <p style="text-align:center"><input type="submit" value="Tìm kiếm" /></p>
    <h3>DANH SÁCH SINH VIÊN</h3>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
         grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaSV","Mã sinh viên"), //the model fields to display
        grid.Column("HoSV","Họ sinh viên"  ),
        grid.Column("TenSV","Tên sinh viên"),
        grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("LOP.MaLop","Mã lớp"),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","SINHVIEN0720_61133181", new { id = item.MaSV },"SINHVIEN0720_61133181Controller")),

}
)
    </div>

}